c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=107
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=110
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=113
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=116
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=119
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=122
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=125
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=128
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=131
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=134
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=137
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=140
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=143
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=146
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=149
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=152
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=155
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=158
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=161
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=164
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=167
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=170
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=173
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=176
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=179
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=182
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=185
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=188
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=191
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=194
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=197
rem c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=200
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=203
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=206
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=209
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=215
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=218
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=221
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=224
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=227
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=230
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=233
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=239
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=242
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=245
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=248
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=251
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=254
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=257
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=260
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=263
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=266
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=269
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=272
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=275
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=278
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=281
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=284
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=287
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=290
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=293
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=296
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=299
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=302
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=305
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=308
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=311
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=314
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=317
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=320
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=323
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=326
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=329
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=332
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=335
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=338
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=341
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=347
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=350
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=353
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=356
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=359
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=362
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=365
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=368
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=371
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=374
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=377
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=380
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=383
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=386
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=389
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=392
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=395
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=398
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=401
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=404
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=410
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=413
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=416
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=422
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=425
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=428
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=431
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=434
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=440
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=443
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=446
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=449
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=452
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=455
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=458
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=461
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=464
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=467
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=473
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=476
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=479
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=482
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=485
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=488
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=491
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=494
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=497
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=500
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=503
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=506
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=512
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=515
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=518
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=521
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=524
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=527
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=530
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=533
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=536
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=539
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=542
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=545
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=548
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=551
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=554
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=557
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=560
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=563
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=566
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=569
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=572
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=575
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=578
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=581
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=584
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=587
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=590
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=593
c:\xampp\php\php.exe c:\xampp\htdocs\city\modules\minion\minion --task=test --id_dev=596
